"""empty message

Revision ID: fca69daea1e4
Revises: a40a45b145c0
Create Date: 2020-03-12 10:21:04.111671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca69daea1e4'
down_revision = 'a40a45b145c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_talent')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
